name: Run updateHelloWorld Script

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or master, or whatever your default branch is

jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Install dependencies
      #   run: npm install  # If your script requires additional npm packages, install them here

      - name: Run updateHelloWorld.js
        run: node updateHelloWorld.js

      - name: Commit and push changes if modified
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update hello-world.txt via GitHub Action"
            git push origin HEAD:${{ github.ref }}
          fi
