name: Update JSON Content

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy and run update script
        run: |
          cd gh-pages
          node updateHelloWorld.js

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add assets/data/youtube.json
          git commit -m "Update youtube.json with new content" || echo "No changes to commit"
          git push origin gh-pages
