name: Update JSON Content
on:
  push:
    branches:
      - main
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create directory structure
        run: mkdir -p assets/data
          
      - name: Run update script
        run: node update-json.js
        
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Copy updated file
        run: |
          mkdir -p gh-pages/assets/data
          cp assets/data/youtube.json gh-pages/assets/data/ || echo "No file to copy"
          
      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/data/youtube.json
          git commit -m "Update youtube.json with new content" || echo "No changes to commit"
          git push origin gh-pages
