name: Read and Update Content

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  read-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis@126.0.1 jsdom axios event-stream JSONStream     

      - name: Get today's year
        run: echo "YEAR=$(date +%Y)" >> 

      - name: Read and Update Content
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}      
        run: |
          # Read and print existing content

          # Generate random paragraph using Node.js
          node updateHelloWorld.js $YEAR

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add assets/data/hello-world.txt
          git commit -m "Update assets/data/hello-world.txt with new paragraph" || echo "No changes to commit"
          git push origin gh-pages
