name: Generate and Push JSON to GH-Pages

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Or your default branch

env:
  GH_PAGES_DIR: 'gh-pages'  # Default value

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Execute JavaScript to Generate JSON
        run: |
          node <<EOF
          const fs = require('fs');
          const data = { "message": "Hello from GitHub Actions!" };
          try {
            fs.writeFileSync('test.json', JSON.stringify(data, null, 2));
            console.log('File test.json has been created successfully.');
          } catch (err) {
            console.error('Failed to write file:', err);
          }
          EOF

      - name: Verify test.json Exists
        run: |
          ls -la
          if [ -f test.json ]; then
            echo "test.json exists"
          else
            echo "test.json does NOT exist"
          fi

      - name: Copy JSON to GH-Pages directory
        run: |
          mkdir -p ${{ env.GH_PAGES_DIR }}
          if [ -f test.json ]; then
            cp test.json ${{ env.GH_PAGES_DIR }}/
          else
            echo "test.json was not found; cannot copy."
          fi

      - name: Checkout GH-Pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          git clean -fd

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes to GH-Pages
        run: |
          cd ${{ env.GH_PAGES_DIR }}
          git add .
          if git status | grep -q "Changes to be committed"; then
            git commit -m "Update JSON file"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
