name: Generate and Deploy Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create hello-world.txt
        run: |
          mkdir -p temp
          node -e "
            const fs = require('fs');
            const content = 'Hello World! Generated at: ' + new Date().toISOString();
            fs.writeFileSync('temp/hello-world.txt', content);
          "

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy new file to gh-pages
        run: |
          cp -r temp/* gh-pages/
          cd gh-pages
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add hello-world.txt" || echo "No changes to commit"
          git push origin gh-pages
