name: Access GH-Pages Directory

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Or your default branch

env:
  GH_PAGES_DIR: 'gh-pages'  # Default value

jobs:
  access-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Checkout the gh-pages branch
          path: ${{ env.GH_PAGES_DIR }}

      - name: List files in GH-Pages directory
        run: |
          echo "GH-Pages directory: ${{ env.GH_PAGES_DIR }}"
          ls -la ${{ env.GH_PAGES_DIR }}

      - name: Print Directory
        run: |
          echo "Directory listing of GH-Pages:"
          find ${{ env.GH_PAGES_DIR }} -type f -print
