name: Read and Update Content

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  read-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Read and Update Content
        run: |
          # Read and print existing content
          if [ -f assets/data/hello-world.txt ]; then
            echo "Current content of assets/data/hello-world.txt:"
            cat assets/data/hello-world.txt
            echo "-------------------"
          else
            echo "assets/data/hello-world.txt does not exist yet"
            echo "Initializing assets/data/hello-world.txt"
            echo "Hello World! Generated at: $(date -u)" > assets/data/hello-world.txt
          fi

          # Generate random paragraph using Node.js
          node updateHelloWorld.js          

          echo "\nUpdated content of assets/data/hello-world.txt:"
          cat assets/data/hello-world.txt

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add assets/data/hello-world.txt
          git commit -m "Update assets/data/hello-world.txt with new paragraph" || echo "No changes to commit"
          git push origin gh-pages
