name: Deploy Liturgy Table Data to GitHub Pages

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 12:00 AM on the 1st of every month
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create directories
      run: |
        mkdir -p _site/assets/data

    - name: Install dependencies
      run: |
        npm init -y
        npm install jsdom
        npm install axios

    - name: Get current year
      id: get_year
      run: echo "::set-output name=year::$(date +'%Y')"

    - name: Run fetch liturgi kalendar
      run: node fetchAndSaveLiturgyTable.js ${{ steps.get_year.outputs.year }}
      env:
        YEAR: ${{ steps.get_year.outputs.year }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./assets/data
        # Add this to ensure we don't clean the existing content
        keep_history: true
        # Optionally, if you want to commit only the changes in ./assets/data
        # external_repository: cryptorichyrich/dekace-action
        # publish_branch: gh-pages
