name: Fetch Data and Push to gh-pages

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Update to at least 15.0.0; here I've used 16 for stability

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis@126.0.1
          npm install JSONStream
          npm install event-stream
          npm install dotenv
          npm install jsdom

      - name: Run fetchdata script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: node fetchdata.js

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
