name: Deploy Calendar Data to GitHub Pages

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 12:00 AM on the 1st of every month
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script to fetch data
      run: fetchAndSaveLiturgyTable.js
      env:
        YEAR: 2025  # You might want to make this dynamic or configurable

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./assets/data
