name: Fetch YouTube Playlists and Deploy

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create directories
        run: |
          mkdir -p _site/assets/data

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis@126.0.1

      - name: Run playlist fetcher
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          echo "Starting playlist fetch..."
          node fetch-playlists.js

      - name: Commit and Push to gh-pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan gh-pages
          git --work-tree . add --all
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
