name: YOUTUBE PLAYLIST
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  

jobs:
  read-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis   
      
      - name: Read and Update Content
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}      
        run: |
          # Read and print existing content
      
          # Generate random paragraph using Node.js
          node fetch-playlists.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "playlist.json" || echo "No changes to commit"
          git push origin gh-pages
