name: YOUTUBE PLAYLIST

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  read-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install youtube-sr puppeteer
          npm i youtube-sr
          npx puppeteer browsers install chrome            
      
      - name: Read and Update Content  
        run: |
          node youtube-sr.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit -m "dkcPlaylists.json" || echo "No changes to commit"
          git push origin gh-pages
